# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171204_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 9, 52, 13, 768020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 9, 52, 13, 767298, tzinfo=utc)),
        ),
    ]
