# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171210_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 22, 42, 446179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 22, 42, 445045, tzinfo=utc)),
        ),
    ]
