# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171210_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 33, 28, 99262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 33, 28, 98296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_imgs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
