# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171210_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 34, 22, 709862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='yaratilma_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 10, 34, 22, 709043, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
